server {
    listen PORT_PLACEHOLDER;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /industries {
        try_files /industries.html =404;
    }
    location = /power-grid {
        try_files /power-grid.html =404;
    }
    location = /data-center {
        try_files /data-center.html =404;
    }
    location = /water-wastewater {
        try_files /water-wastewater.html =404;
    }
    location = /industrial {
        try_files /industrial.html =404;
    }
    location = /defense {
        try_files /defense.html =404;
    }
    location = /nuclear {
        try_files /nuclear.html =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
